"""add document split strategy

Revision ID: 7d1b6a4e2f90
Revises: 4c0b10f71d9d
Create Date: 2025-07-29 10:55:13

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '7d1b6a4e2f90'
down_revision = '4c0b10f71d9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('split_strategy', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('split_strategy')

    # ### end Alembic commands ###
